### PR TITLE
Merge davisp/1.0.8

### PR DESCRIPTION
**Pull request by ypisetsky**
This catches this repo up to upstream's 1.0.8 tag (around 4 years worth of changes/fixes). It maintains the patches that existed from before. I'm not convinced a merge commit is the best way to do this, but open to ideas.

### CODE REVIEW

**Comment by ypisetsky** [comment]
This is hard to read in this direction. https://gist.github.com/ypisetsky/149fdc93afcf971894a4691bb796abcd shows the patch as compared to upstream's 1.0.8 tag.

**Comment by mezz** [comment]
I usually like merging for this type of catch-up, but I think in this case we haven't changed much compared to upstream, so it may make it hard to find our changes in the noise later (it's already hard to find them in this PR heh). 

If it's not too much work (i.e. if you didn't have many code conflicts when creating this) we can: 
* create a new `discord-1.0.8` branch that's starting at upstream's `1.0.8` tag
* rebase or cherry-pick all of our commits on top of that 
* make a PR to review merging those changes into `discord-1.0.8`
* update the "main" branch in github to be `discord-1.0.8` instead of `master` so the changes are more easily visible on github

**Comment by ypisetsky** [comment]
https://github.com/discord/jiffy/pull/6 for the other direction. Regardless it's the same commit being pushed to master.

**Comment by ypisetsky** [comment]
Ended up manually rebasing the old master on top of upstream's 1.0.8

**Pull request closed without merging**
